# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeActions', '0002_remove_category_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeaction',
            name='image',
            field=models.ImageField(blank=True, height_field=200, upload_to='', width_field=150),
        ),
    ]
