# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeActions', '0003_auto_20170609_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeaction',
            name='isCompleted',
        ),
    ]
